services:
  pdf-app:
    build: .
    container_name: pdf-distributor
    restart: always
    ports:
      - "10031:10031"
    env_file:
      - .env
    volumes:
      - ./baidu_token.json:/app/baidu_token.json
      - ./output_cache:/app/output_cache
    environment:
      - TZ=Asia/Shanghai
